### ISSUE TITLE
Default signatures

### ISSUE THREAD

**Issue by domenkozar** [sellerlabs/monad-metrics#12]
Hey @parsonsmatt :) 

I really like this library, fits well into the rest of my stack. But one thing really bothers me:

```haskell
gauge :: (MonadIO m, MonadMetrics m) => Text -> Int -> m ()
gauge' :: (MonadIO m, MonadMetrics m, Integral int) => Text -> int -> m ()
```
Both of these exists since 0.1, what's the reasoning behind it? I'd prefer if `gauge'` was just `gauge` and no default existed. And if it did, it should probably be `Integer`?

**Comment by parsonsmatt** [comment]
Thank you!

I initially had only the most polymorphic one, and had to silence tons of type defaulting warnings, almost always with `Int`. So I made the default work with `Int` and a more generic one that worked with any Integral. I rarely used the `guage'` function, but when I did, it was using some value that had a type fixed by some other part of the code, and thus didn't need the annotation.

**Comment by domenkozar** [comment]
I'm tracking some data in the number of bytes, so `Int` would overflow :) What about type application to silence warnings? I'd be happy with:

```haskell
gauge :: (MonadIO m, MonadMetrics m, Integral int) => Text -> int -> m ()
gaugeInteger :: (MonadIO m, MonadMetrics m) => Text -> Integer -> m ()
```

**Comment by parsonsmatt** [comment]
Type applications are a good idea, but this would break the symmetry with the other function names (where the plain one is the "sensible default" and the ticked one is the more generic/customizable one).

I'd be happy to use `ExplicitForall` to switch the type variable ordering so `gauge' :: forall int m. (MonadIO m, MonadMetrics m, Integral int) => Text -> int -> m ()`, which would allow you to write `guage' @Integer "foo" 1234`. This is a breaking change, but less dramatic than changing the actual types or names of functions, and I wouldn't be opposed to it.

I would want to see evidence that generalizing `gauge` would not result in builds breaking with `-Wall` before making that change.

**Comment by domenkozar** [comment]
What bothers me is the choice of naming (and default types), but if you're not willing to break backwards compatibility, then there's not much point discussing :)

**Comment by parsonsmatt** [comment]
One thing to note: this library's design was to be imported qualified, partially so end users could define their own customizations. If you want, you can write:

```haskell
module MyMetrics 
    ( module MyMetrics
    , M.counter
    -- etc
    ) where

import qualified Control.Monad.Metrics as M

gauge :: (MonadIO m, MonadMetrics m) =>  Text -> Integer -> m ()
gauge = M.guage'
```

and then `MyMetrics` is a drop-in customization for `Control.Monad.Metrcs` but with the types you want :)

**Comment by domenkozar** [comment]
I can live with `gauge'`, maybe you could keep a TODO list for 1.0 if you ever want to do that :) Thanks!
